version: '3.8'
services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8081:8080
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=visroot@4
  db:
    container_name: db
    image: mysql:latest
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=visroot@4
      - MYSQL_DATABASE=anon
      - MYSQL_PASSWORD=visroot@4
